@host = localhost:8080

// Create Product
POST http://{{host}}/api/products HTTP/1.1
content-type: application/json
    
{
    "name": "product",
    "description": "description",
    "price": 100.00
}

###

// Get Product By ID
GET http://{{host}}/api/products/2 HTTP/1.1
content-type: application/json

###

// Get All Products
GET http://{{host}}/api/products/ HTTP/1.1
content-type: application/json

###

// Update Product
PUT http://{{host}}/api/products/2 HTTP/1.1
content-type: application/json

{
    "name": "updated-product",
    "description": "random-description-updated",
    "price": 100.00
}

###

// Delete Product
DELETE http://{{host}}/api/products/3 HTTP/1.1
content-type: application/json

###

// Create category
    
POST http://{{host}}/api/category HTTP/1.1
conetent-type: application/json

{
    "name": "Category",
    "color": "red"
}

###

// Get category by id

GET http://{{host}}/api/category/0 HTTP/1.1
content-type: application/json

###

// Get all categories

GET http://{{host}}/api/category/ HTTP/1.1
content-type: application/json

###

// Update category

POST http://{{host}}/api/category/2 HTTP/1.1
content-type: application/json

###

// Delete category

DELETE http://{{host}}/api/category/2 HTTP/1.1
content-type: application/json